name: example-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - scipy
  - spoisson
#  - pip
#  - pip:
#     - poisson
#    - notebook-as-pdf==0.5.0
